run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - bodyclose
    - noctx
    - exportloopref

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/CastAIPhil/AUTO
  misspell:
    locale: US
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - unparam
    - path: mock\.go
      linters:
        - unused

output:
  formats:
    - format: colored-line-number
  sort-results: true
